name: drones_detections
channels:
  - hcc
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.8.1=py36_0
  - astor=0.8.0=py36_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py36_0
  - beautifulsoup4=4.8.1=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.7.22=0
  - cairo=1.14.12=h8948797_3
  - certifi=2020.6.20=py36_0
  - cloudpickle=1.2.2=py_0
  - cudatoolkit=9.0=h13b8566_0
  - cudnn=7.1.2=cuda9.0_0
  - cupti=9.0.176=0
  - cycler=0.10.0=py36_0
  - cython=0.29.15=py36he6710b0_0
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask-core=2.8.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - dm-sonnet-gpu=1.23=py36h878f04b_1
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - gast=0.3.2=py_0
  - geos=3.8.0=he6710b0_0
  - glib=2.63.1=h5a9c865_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - imageio=2.6.1=py36_0
  - importlib_metadata=0.23=py36_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.3=py36h39e3cac_0
  - ipython=7.9.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.5.1=py_0
  - jasper=2.0.14=h07fcdf6_1
  - jedi=0.15.1=py36_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.0=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.8.5=py_0
  - jsonschema=3.1.1=py36_0
  - jupyter_client=5.3.4=py36_0
  - jupyter_core=4.6.1=py36_0
  - jupyterlab=1.1.4=pyhf63ae98_0
  - jupyterlab_server=1.0.6=py_0
  - keras-applications=1.0.8=py_0
  - keras-gpu=2.0.8=py36h0585f72_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libllvm10=10.0.1=hbcb73fb_5
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - llvmlite=0.34.0=py36h269e1b5_4
  - markdown=3.1.1=py36_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - matplotlib=3.1.1=py36h5429711_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - more-itertools=7.2.0=py36_0
  - mypy=0.782=py_0
  - mypy_extensions=0.4.3=py36_0
  - nbconvert=5.6.1=py36_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - nodejs=12.4.0=he1b5a44_0
  - notebook=6.0.1=py36_0
  - numba=0.51.2=py36h0573a6f_1
  - numpy=1.17.3=py36hd14ec0e_0
  - numpy-base=1.17.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1h=h7b6447c_0
  - pandas=0.25.2=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - pango=1.42.4=h049681c_0
  - parso=0.5.1=py_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.2.1=py36h34e0f95_0
  - pip=19.3.1=py36_0
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - protobuf=3.9.2=py36he6710b0_0
  - psutil=5.7.2=py36h7b6447c_0
  - ptyprocess=0.6.0=py36_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pydensecrf=1.0rc3=py36hf8a1672_1
  - pydot=1.4.1=py36_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.15.4=py36h7b6447c_0
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py36h7b6447c_0
  - pyyaml=5.1.2=py36h7b6447c_0
  - pyzmq=18.1.0=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-image=0.15.0=py36he6710b0_0
  - scikit-learn=0.21.3=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=41.6.0=py36_0
  - shapely=1.7.0=py36h98ec03d_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - soupsieve=1.9.4=py36_0
  - sqlite=3.30.1=h7b6447c_0
  - statsmodels=0.10.1=py36hdd07704_0
  - tbb=2020.3=hfd86e86_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he68c306_0
  - tensorflow-base=1.12.0=gpu_py36h8e0ae2d_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h7b6447c_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py36_0
  - typed-ast=1.4.1=py36h7b6447c_0
  - typing_extensions=3.7.4.3=py_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py36_0
  - widgetsnbextension=3.5.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - opencv-contrib-python==3.4.2.17
